version: '3.4'

services:
  reservationmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8280
      - ASPNETCORE_HTTPS_PORTS=8281
    ports:
      - 8280:8280
      - 8281:8281
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  restaurantmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
      - ASPNETCORE_HTTPS_PORTS=8181
    ports:
      - 8180:8180
      - 8181:8181
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  usermanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8380
      - ASPNETCORE_HTTPS_PORTS=8381
    ports:
      - 8380:8380
      - 8381:8381
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  database:
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"

  sql-server:
    ports:
      - 1433:1433
    volumes:
      - ./.docker/mssql/data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}

  adminer:
    ports:
      - 8888:8080